### ISSUE TITLE
Error: Can't execute "PRAGMA journal_mode = DELETE": attempt to write a readonly database

### ISSUE THREAD

**Issue by rugosnafu** [Homegear/Homegear-Beckhoff#1]
Hi,

after running homegear for several days I installed the new version 0.6.3-1415. The Server does not start and in the log I found the following lines:

07/15/16 13:25:03.321 Starting Homegear...
07/15/16 13:25:03.321 Homegear version 0.6.3-1415
07/15/16 13:25:03.321 Git commit SHA of libhomegear-base: -
07/15/16 13:25:03.321 Git branch of libhomegear-base:     -
07/15/16 13:25:03.321 Git commit SHA of Homegear:         -
07/15/16 13:25:03.322 Git branch of Homegear:             -
07/15/16 13:25:03.340 Info: Backing up database...
07/15/16 13:25:03.461 Initializing database...
07/15/16 13:25:03.472 Info: Loading family module mod_miscellaneous.so
07/15/16 13:25:03.477 /etc/homegear/families/miscellaneous.conf
07/15/16 13:25:03.478 Info: Loading family module mod_homematicbidcos.so
07/15/16 13:25:03.496 /etc/homegear/families/homematicbidcos.conf
07/15/16 13:25:03.497 Unable to open family setting file: /etc/homegear/families/homematicbidcos.conf. No such file or directory
07/15/16 13:25:03.498 Info: Setting up physical interfaces and GPIOs...
07/15/16 13:25:03.498 Info: Dropping privileges to user homegear (111) and group homegear (116)
07/15/16 13:25:03.499 Info: Homegear is (now) running as user with id 111 and group with id 116.
07/15/16 13:25:03.499 Info: Setting allowed core file size to "4294967295" for user with id 111 and group with id 116.
07/15/16 13:25:03.499 Info: Core file size now is "4294967295".
07/15/16 13:25:03.499 Info: Setting maximum thread priority to "4294967295" for user with id 111 and group with id 116.
07/15/16 13:25:03.499 Info: Maximum thread priority now is "4294967295".
07/15/16 13:25:03.500 Error in file main.cpp line 975 in function void startUp(): Could not open directory.
07/15/16 13:25:03.501 Info: Disposing family module mod_miscellaneous.so
07/15/16 13:25:03.501 Info: Disposing family module mod_homematicbidcos.so
07/15/16 13:25:03.503 Closing database...
07/15/16 13:25:03.504 Error: Can't execute "PRAGMA journal_mode = DELETE": attempt to write a readonly database

I' am running homegear on a raspi using raspian. Can anybody give me a hint? 

best regards
Christoph

**Comment by hfedcba** [comment]
This should be in Homegear/Homegear ;-). Your Homegear can't open /var/lib/homegear. What is the owner of that directory? What are the permissions? I added a fix to the current source code, so that the error message is more clear and Homegear tries to continue starting.

**Comment by rugosnafu** [comment]
HI,

these are the settings:

drw-rw----  7 homegear homegear 4096 Jul 15 14:15 homegear

cu Christoph

**Comment by hfedcba** [comment]
ok, thanks - outch. It's fixed now. I will start compiling the new version asap.
